version: "3.8"

volumes:
  db-store:

services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-ci4}
      - DB_USERNAME=${DB_USER:-ci4}
      - DB_PASSWORD=${DB_PASS:-ci4}

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-ci4}
      - MYSQL_USER=${DB_USER:-ci4}
      - MYSQL_PASSWORD=${DB_PASS:-ci4}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
